name: Generate Docs

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install google-generativeai
      - name: Generate documentation
        run: python generate_docs.py
      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md $(find Problemas -name README.md -print)
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update docs"
            git push
          fi
